from curses import (COLOR_BLACK, COLOR_BLUE, COLOR_CYAN, COLOR_GREEN,
                    COLOR_MAGENTA, COLOR_RED, COLOR_WHITE, COLOR_YELLOW)

LINES = 13
COLUMNS = 13

SNAKE_CHAR = "O"
SNAKE_COLOR = COLOR_GREEN
INITIAL_SIZE = 2

APPLE_CHAR = "*"
APPLE_COLOR = COLOR_RED

EMPTY_CHAR = "'"
EMPTY_COLOR = COLOR_WHITE

REFRESH_TIME = 0.1 # seconds

TEXT_COLOR = COLOR_YELLOW
