import curses # imports colours

LINES = 13
COLUMNS = 13

INITIAL_SIZE = 3

EMPTY_CHAR = "'"
EMPTY_COLOR = curses.COLOR_WHITE

SNAKE_CHAR = "O"
SNAKE_COLOR = curses.COLOR_GREEN

APPLE_CHAR = "*"
APPLE_COLOR = curses.COLOR_RED

TEXT_COLOR = curses.COLOR_YELLOW

REFRESH_TIME = 0.1 # seconds
EXIT_KEY = "q"

GAME_OVER_TIME = 3 # seconds
GAME_OVER_MESSAGE = "GAME OVER!"
